apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-service
  namespace: default
spec:
  ports:
  - nodePort: 30657
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: myapp
  type: LoadBalancer
